version: '3.8'

services:

  back:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgre_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      CORS_ORIGINS: http://localhost;http://localhost:4200;http://localhost:8000;

  postgre_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123

    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgre_db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  pgdata: